import type { AppProps } from 'next/app'
import '@vercel/examples-ui/globals.css'

export const metadata = {
  title: "Weather App with Cookies",
  description: "Generated by create next app",
};

function App({ Component, pageProps }: AppProps) {
  return (
    <Component {...pageProps} />
  )
}

export default App
